#include "countries.h"

namespace countries{

    QString getCountryNameISO3166(const QString &code) {

        static const QHash<QString,QString> country{
            { QStringLiteral("AF") , QStringLiteral("Afghanistan")},
            { QStringLiteral("AX") , QStringLiteral("Åland Islands")},
            { QStringLiteral("AL") , QStringLiteral("Albania")},
            { QStringLiteral("DZ") , QStringLiteral("Algeria")},
            { QStringLiteral("AS") , QStringLiteral("American Samoa")},
            { QStringLiteral("AD") , QStringLiteral("Andorra")},
            { QStringLiteral("AO") , QStringLiteral("Angola")},
            { QStringLiteral("AI") , QStringLiteral("Anguilla")},
            { QStringLiteral("AQ") , QStringLiteral("Antarctica")},
            { QStringLiteral("AG") , QStringLiteral("Antigua and Barbuda")},
            { QStringLiteral("AR") , QStringLiteral("Argentina")},
            { QStringLiteral("AM") , QStringLiteral("Armenia")},
            { QStringLiteral("AW") , QStringLiteral("Aruba")},
            { QStringLiteral("AU") , QStringLiteral("Australia")},
            { QStringLiteral("AT") , QStringLiteral("Austria")},
            { QStringLiteral("AZ") , QStringLiteral("Azerbaijan")},
            { QStringLiteral("BS") , QStringLiteral("Bahamas")},
            { QStringLiteral("BH") , QStringLiteral("Bahrain")},
            { QStringLiteral("BD") , QStringLiteral("Bangladesh")},
            { QStringLiteral("BB") , QStringLiteral("Barbados")},
            { QStringLiteral("BY") , QStringLiteral("Belarus")},
            { QStringLiteral("BE") , QStringLiteral("Belgium")},
            { QStringLiteral("BZ") , QStringLiteral("Belize")},
            { QStringLiteral("BJ") , QStringLiteral("Benin")},
            { QStringLiteral("BM") , QStringLiteral("Bermuda")},
            { QStringLiteral("BT") , QStringLiteral("Bhutan")},
            { QStringLiteral("BO") , QStringLiteral("Bolivia")},
            { QStringLiteral("BA") , QStringLiteral("Bosnia and Herzegovina")},
            { QStringLiteral("BW") , QStringLiteral("Botswana")},
            { QStringLiteral("BV") , QStringLiteral("Bouvet Island")},
            { QStringLiteral("BR") , QStringLiteral("Brazil")},
            { QStringLiteral("IO") , QStringLiteral("British Indian Ocean Territory")},
            { QStringLiteral("BN") , QStringLiteral("Brunei Darussalam")},
            { QStringLiteral("BG") , QStringLiteral("Bulgaria")},
            { QStringLiteral("BF") , QStringLiteral("Burkina Faso")},
            { QStringLiteral("BI") , QStringLiteral("Burundi")},
            { QStringLiteral("KH") , QStringLiteral("Cambodia")},
            { QStringLiteral("CM") , QStringLiteral("Cameroon")},
            { QStringLiteral("CA") , QStringLiteral("Canada")},
            { QStringLiteral("CV") , QStringLiteral("Cape Verde")},
            { QStringLiteral("KY") , QStringLiteral("Cayman Islands")},
            { QStringLiteral("CF") , QStringLiteral("Central African Republic")},
            { QStringLiteral("TD") , QStringLiteral("Chad")},
            { QStringLiteral("CL") , QStringLiteral("Chile")},
            { QStringLiteral("CN") , QStringLiteral("China")},
            { QStringLiteral("CX") , QStringLiteral("Christmas Island")},
            { QStringLiteral("CC") , QStringLiteral("Cocos (Keeling) Islands")},
            { QStringLiteral("CO") , QStringLiteral("Colombia")},
            { QStringLiteral("KM") , QStringLiteral("Comoros")},
            { QStringLiteral("CG") , QStringLiteral("Congo")},
            { QStringLiteral("CD") , QStringLiteral("Congo, the Democratic Republic of the")},
            { QStringLiteral("CK") , QStringLiteral("Cook Islands")},
            { QStringLiteral("CR") , QStringLiteral("Costa Rica")},
            { QStringLiteral("CI") , QStringLiteral("Côte D'Ivoire")},
            { QStringLiteral("HR") , QStringLiteral("Croatia")},
            { QStringLiteral("CU") , QStringLiteral("Cuba")},
            { QStringLiteral("CY") , QStringLiteral("Cyprus")},
            { QStringLiteral("CZ") , QStringLiteral("Czech Republic")},
            { QStringLiteral("DK") , QStringLiteral("Denmark")},
            { QStringLiteral("DJ") , QStringLiteral("Djibouti")},
            { QStringLiteral("DM") , QStringLiteral("Dominica")},
            { QStringLiteral("DO") , QStringLiteral("Dominican Republic")},
            { QStringLiteral("EC") , QStringLiteral("Ecuador")},
            { QStringLiteral("EG") , QStringLiteral("Egypt")},
            { QStringLiteral("SV") , QStringLiteral("El Salvador")},
            { QStringLiteral("GQ") , QStringLiteral("Equatorial Guinea")},
            { QStringLiteral("ER") , QStringLiteral("Eritrea")},
            { QStringLiteral("EE") , QStringLiteral("Estonia")},
            { QStringLiteral("ET") , QStringLiteral("Ethiopia")},
            { QStringLiteral("FK") , QStringLiteral("Falkland Islands (Malvinas)")},
            { QStringLiteral("FO") , QStringLiteral("Faroe Islands")},
            { QStringLiteral("FJ") , QStringLiteral("Fiji")},
            { QStringLiteral("FI") , QStringLiteral("Finland")},
            { QStringLiteral("FR") , QStringLiteral("France")},
            { QStringLiteral("GF") , QStringLiteral("French Guiana")},
            { QStringLiteral("PF") , QStringLiteral("French Polynesia")},
            { QStringLiteral("TF") , QStringLiteral("French Southern Territories")},
            { QStringLiteral("GA") , QStringLiteral("Gabon")},
            { QStringLiteral("GM") , QStringLiteral("Gambia")},
            { QStringLiteral("GE") , QStringLiteral("Georgia")},
            { QStringLiteral("DE") , QStringLiteral("Germany")},
            { QStringLiteral("GH") , QStringLiteral("Ghana")},
            { QStringLiteral("GI") , QStringLiteral("Gibraltar")},
            { QStringLiteral("GR") , QStringLiteral("Greece")},
            { QStringLiteral("GL") , QStringLiteral("Greenland")},
            { QStringLiteral("GD") , QStringLiteral("Grenada")},
            { QStringLiteral("GP") , QStringLiteral("Guadeloupe")},
            { QStringLiteral("GU") , QStringLiteral("Guam")},
            { QStringLiteral("GT") , QStringLiteral("Guatemala")},
            { QStringLiteral("GG") , QStringLiteral("Guernsey")},
            { QStringLiteral("GN") , QStringLiteral("Guinea")},
            { QStringLiteral("GW") , QStringLiteral("Guinea-Bissau")},
            { QStringLiteral("GY") , QStringLiteral("Guyana")},
            { QStringLiteral("HT") , QStringLiteral("Haiti")},
            { QStringLiteral("HM") , QStringLiteral("Heard Island and Mcdonald Islands")},
            { QStringLiteral("VA") , QStringLiteral("Holy See (Vatican City State)")},
            { QStringLiteral("HN") , QStringLiteral("Honduras")},
            { QStringLiteral("HK") , QStringLiteral("Hong Kong")},
            { QStringLiteral("HU") , QStringLiteral("Hungary")},
            { QStringLiteral("IS") , QStringLiteral("Iceland")},
            { QStringLiteral("IN") , QStringLiteral("India")},
            { QStringLiteral("ID") , QStringLiteral("Indonesia")},
            { QStringLiteral("IR") , QStringLiteral("Iran, Islamic Republic of")},
            { QStringLiteral("IQ") , QStringLiteral("Iraq")},
            { QStringLiteral("IE") , QStringLiteral("Ireland")},
            { QStringLiteral("IM") , QStringLiteral("Isle of Man")},
            { QStringLiteral("IL") , QStringLiteral("Israel")},
            { QStringLiteral("IT") , QStringLiteral("Italy")},
            { QStringLiteral("JM") , QStringLiteral("Jamaica")},
            { QStringLiteral("JP") , QStringLiteral("Japan")},
            { QStringLiteral("JE") , QStringLiteral("Jersey")},
            { QStringLiteral("JO") , QStringLiteral("Jordan")},
            { QStringLiteral("KZ") , QStringLiteral("Kazakhstan")},
            { QStringLiteral("KE") , QStringLiteral("KENYA")},
            { QStringLiteral("KI") , QStringLiteral("Kiribati")},
            { QStringLiteral("KP") , QStringLiteral("Korea, Democratic People's Republic of")},
            { QStringLiteral("KR") , QStringLiteral("Korea, Republic of")},
            { QStringLiteral("KW") , QStringLiteral("Kuwait")},
            { QStringLiteral("KG") , QStringLiteral("Kyrgyzstan")},
            { QStringLiteral("LA") , QStringLiteral("Lao People's Democratic Republic")},
            { QStringLiteral("LV") , QStringLiteral("Latvia")},
            { QStringLiteral("LB") , QStringLiteral("Lebanon")},
            { QStringLiteral("LS") , QStringLiteral("Lesotho")},
            { QStringLiteral("LR") , QStringLiteral("Liberia")},
            { QStringLiteral("LY") , QStringLiteral("Libyan Arab Jamahiriya")},
            { QStringLiteral("LI") , QStringLiteral("Liechtenstein")},
            { QStringLiteral("LT") , QStringLiteral("Lithuania")},
            { QStringLiteral("LU") , QStringLiteral("Luxembourg")},
            { QStringLiteral("MO") , QStringLiteral("Macao")},
            { QStringLiteral("MK") , QStringLiteral("Macedonia, the Former Yugoslav Republic of")},
            { QStringLiteral("MG") , QStringLiteral("Madagascar")},
            { QStringLiteral("MW") , QStringLiteral("Malawi")},
            { QStringLiteral("MY") , QStringLiteral("Malaysia")},
            { QStringLiteral("MV") , QStringLiteral("Maldives")},
            { QStringLiteral("ML") , QStringLiteral("Mali")},
            { QStringLiteral("MT") , QStringLiteral("Malta")},
            { QStringLiteral("MH") , QStringLiteral("Marshall Islands")},
            { QStringLiteral("MQ") , QStringLiteral("Martinique")},
            { QStringLiteral("MR") , QStringLiteral("Mauritania")},
            { QStringLiteral("MU") , QStringLiteral("Mauritius")},
            { QStringLiteral("YT") , QStringLiteral("Mayotte")},
            { QStringLiteral("MX") , QStringLiteral("Mexico")},
            { QStringLiteral("FM") , QStringLiteral("Micronesia, Federated States of")},
            { QStringLiteral("MD") , QStringLiteral("Moldova, Republic of")},
            { QStringLiteral("MC") , QStringLiteral("Monaco")},
            { QStringLiteral("MN") , QStringLiteral("Mongolia")},
            { QStringLiteral("ME") , QStringLiteral("Montenegro")},
            { QStringLiteral("MS") , QStringLiteral("Montserrat")},
            { QStringLiteral("MA") , QStringLiteral("Morocco")},
            { QStringLiteral("MZ") , QStringLiteral("Mozambique")},
            { QStringLiteral("MM") , QStringLiteral("Myanmar")},
            { QStringLiteral("NA") , QStringLiteral("Namibia")},
            { QStringLiteral("NR") , QStringLiteral("Nauru")},
            { QStringLiteral("NP") , QStringLiteral("Nepal")},
            { QStringLiteral("NL") , QStringLiteral("Netherlands")},
            { QStringLiteral("AN") , QStringLiteral("Netherlands Antilles")},
            { QStringLiteral("NC") , QStringLiteral("New Caledonia")},
            { QStringLiteral("NZ") , QStringLiteral("New Zealand")},
            { QStringLiteral("NI") , QStringLiteral("Nicaragua")},
            { QStringLiteral("NE") , QStringLiteral("Niger")},
            { QStringLiteral("NG") , QStringLiteral("Nigeria")},
            { QStringLiteral("NU") , QStringLiteral("Niue")},
            { QStringLiteral("NF") , QStringLiteral("Norfolk Island")},
            { QStringLiteral("MP") , QStringLiteral("Northern Mariana Islands")},
            { QStringLiteral("NO") , QStringLiteral("Norway")},
            { QStringLiteral("OM") , QStringLiteral("Oman")},
            { QStringLiteral("PK") , QStringLiteral("Pakistan")},
            { QStringLiteral("PW") , QStringLiteral("Palau")},
            { QStringLiteral("PS") , QStringLiteral("Palestinian Territory, Occupied")},
            { QStringLiteral("PA") , QStringLiteral("Panama")},
            { QStringLiteral("PG") , QStringLiteral("Papua New Guinea")},
            { QStringLiteral("PY") , QStringLiteral("Paraguay")},
            { QStringLiteral("PE") , QStringLiteral("Peru")},
            { QStringLiteral("PH") , QStringLiteral("Philippines")},
            { QStringLiteral("PN") , QStringLiteral("Pitcairn")},
            { QStringLiteral("PL") , QStringLiteral("Poland")},
            { QStringLiteral("PT") , QStringLiteral("Portugal")},
            { QStringLiteral("PR") , QStringLiteral("Puerto Rico")},
            { QStringLiteral("QA") , QStringLiteral("Qatar")},
            { QStringLiteral("RE") , QStringLiteral("Réunion")},
            { QStringLiteral("RO") , QStringLiteral("Romania")},
            { QStringLiteral("RU") , QStringLiteral("Russian Federation")},
            { QStringLiteral("RW") , QStringLiteral("Rwanda")},
            { QStringLiteral("SH") , QStringLiteral("Saint Helena")},
            { QStringLiteral("KN") , QStringLiteral("Saint Kitts and Nevis")},
            { QStringLiteral("LC") , QStringLiteral("Saint Lucia")},
            { QStringLiteral("PM") , QStringLiteral("Saint Pierre and Miquelon")},
            { QStringLiteral("VC") , QStringLiteral("Saint Vincent and the Grenadines")},
            { QStringLiteral("WS") , QStringLiteral("Samoa")},
            { QStringLiteral("SM") , QStringLiteral("San Marino")},
            { QStringLiteral("ST") , QStringLiteral("Sao Tome and Principe")},
            { QStringLiteral("SA") , QStringLiteral("Saudi Arabia")},
            { QStringLiteral("SN") , QStringLiteral("Senegal")},
            { QStringLiteral("RS") , QStringLiteral("Serbia")},
            { QStringLiteral("SC") , QStringLiteral("Seychelles")},
            { QStringLiteral("SL") , QStringLiteral("Sierra Leone")},
            { QStringLiteral("SG") , QStringLiteral("Singapore")},
            { QStringLiteral("SK") , QStringLiteral("Slovakia")},
            { QStringLiteral("SI") , QStringLiteral("Slovenia")},
            { QStringLiteral("SB") , QStringLiteral("Solomon Islands")},
            { QStringLiteral("SO") , QStringLiteral("Somalia")},
            { QStringLiteral("ZA") , QStringLiteral("South Africa")},
            { QStringLiteral("GS") , QStringLiteral("South Georgia and the South Sandwich Islands")},
            { QStringLiteral("ES") , QStringLiteral("Spain")},
            { QStringLiteral("LK") , QStringLiteral("Sri Lanka")},
            { QStringLiteral("SD") , QStringLiteral("Sudan")},
            { QStringLiteral("SR") , QStringLiteral("Suriname")},
            { QStringLiteral("SJ") , QStringLiteral("Svalbard and Jan Mayen")},
            { QStringLiteral("SZ") , QStringLiteral("Swaziland")},
            { QStringLiteral("SE") , QStringLiteral("Sweden")},
            { QStringLiteral("CH") , QStringLiteral("Switzerland")},
            { QStringLiteral("SY") , QStringLiteral("Syrian Arab Republic")},
            { QStringLiteral("TW") , QStringLiteral("Taiwan, Province of China")},
            { QStringLiteral("TJ") , QStringLiteral("Tajikistan")},
            { QStringLiteral("TZ") , QStringLiteral("Tanzania, United Republic of")},
            { QStringLiteral("TH") , QStringLiteral("Thailand")},
            { QStringLiteral("TL") , QStringLiteral("Timor-Leste")},
            { QStringLiteral("TG") , QStringLiteral("Togo")},
            { QStringLiteral("TK") , QStringLiteral("Tokelau")},
            { QStringLiteral("TO") , QStringLiteral("Tonga")},
            { QStringLiteral("TT") , QStringLiteral("Trinidad and Tobago")},
            { QStringLiteral("TN") , QStringLiteral("Tunisia")},
            { QStringLiteral("TR") , QStringLiteral("Turkey")},
            { QStringLiteral("TM") , QStringLiteral("Turkmenistan")},
            { QStringLiteral("TC") , QStringLiteral("Turks and Caicos Islands")},
            { QStringLiteral("TV") , QStringLiteral("Tuvalu")},
            { QStringLiteral("UG") , QStringLiteral("Uganda")},
            { QStringLiteral("UA") , QStringLiteral("Ukraine")},
            { QStringLiteral("AE") , QStringLiteral("United Arab Emirates")},
            { QStringLiteral("GB") , QStringLiteral("United Kingdom")},
            { QStringLiteral("US") , QStringLiteral("United States")},
            { QStringLiteral("UM") , QStringLiteral("United States Minor Outlying Islands")},
            { QStringLiteral("UY") , QStringLiteral("Uruguay")},
            { QStringLiteral("UZ") , QStringLiteral("Uzbekistan")},
            { QStringLiteral("VU") , QStringLiteral("Vanuatu")},
            { QStringLiteral("VA") , QStringLiteral("Vatican City State")},
            { QStringLiteral("VE") , QStringLiteral("Venezuela")},
            { QStringLiteral("VN") , QStringLiteral("Viet Nam")},
            { QStringLiteral("VG") , QStringLiteral("Virgin Islands, British")},
            { QStringLiteral("VI") , QStringLiteral("Virgin Islands, U.S.")},
            { QStringLiteral("WF") , QStringLiteral("Wallis and Futuna")},
            { QStringLiteral("EH") , QStringLiteral("Western Sahara")},
            { QStringLiteral("YE") , QStringLiteral("Yemen")},
            { QStringLiteral("CD") , QStringLiteral("Zaire")},
            { QStringLiteral("ZM") , QStringLiteral("Zambia")},
            { QStringLiteral("ZW") , QStringLiteral("Zimbabwe")}
        };

        if(country.contains(code)) return country[code];
        if(code == QStringLiteral("_ALL")) return QStringLiteral("Global");

        return QStringLiteral("Other");
    }
}
