CREATE TABLE BOT_COOKIE_CACHE(bot_id INTEGER, key TEXT, domain TEXT, path TEXT, expire TEXT, value TEXT);
ALTER TABLE BOT ADD COLUMN description TEXT;
ALTER TABLE BOT ADD COLUMN link TEXT;
ALTER TABLE BOT ADD COLUMN icon TEXT;
