# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       phonehook

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    PhoneHook
Version:    0.2.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        https://github.com/omnight/phonehook
Source0:    %{name}-%{version}.tar.bz2
Source100:  phonehook.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   patch
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  desktop-file-utils
BuildRequires:  systemd

%description
See who's calling!

                                                                \

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup


%pre
# >> pre
# clean up patch that breaks connect-to-internet dialog
if more /usr/share/lipstick-jolla-home-qt5/compositor.qml | grep com.omnight.lipstickIf; then
    patch -R -N /usr/share/lipstick-jolla-home-qt5/compositor.qml < /usr/share/phonehook/phonehook-lipstick-v2.patch;
fi
# << pre

%post
# >> post
killall phonehook-daemon
cd /usr/share/lipstick-jolla-home-qt5/
patch -N -p4  < /usr/share/phonehook/phonehook-lipstick-v3.patch;
ln -s -f /usr/lib/systemd/user/phonehook-daemon.service /usr/lib/systemd/user/post-user-session.target.wants
systemctl-user enable phonehook-daemon.service || true
systemctl-user daemon-reload || true
# << post

%postun
# >> postun
if [ "$1" -eq 0 ]; then
killall phonehook-daemon || true
killall phonehook || true
systemctl-user disable phonehook-daemon.service || true
rm /usr/lib/systemd/user/post-user-session.target.wants/phonehook-daemon.service
fi
systemctl-user daemon-reload || true
# << postun

%preun
# >> preun
cd /usr/share/lipstick-jolla-home-qt5/
patch -R -N -p4 < /usr/share/phonehook/phonehook-lipstick-v3.patch;
# << preun

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
/usr/lib/systemd/user/phonehook-daemon.service
# >> files
# << files
